# l id de l'objet la cest une larme de ghast:
id: "370:0"

# Identifiants : (popup, tip ou title):
message-position: "popup"

# Messages:
 # {chestCount} nombre de coffre.
 # {chestDistance} distance du coffre le plus proche du joueur.
 # {lineBreak} Pour faire une ligne en dessous.
no-chest: "§aucun coffre vers vous..."
chest-detected: "§aIl y a {chestCount} {lineBreak} le plus prêt est a  {chestDistance} block !"

# La distance de détection en block:
radius: 70

repeat: 1

# Version de plugins, TOUCHE Y PAS !!!!!
version: "1.5"
